# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alister\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\coveragebuilder\ui_about_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About_window(object):
    def setupUi(self, About_window):
        About_window.setObjectName("About_window")
        About_window.resize(490, 213)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(About_window.sizePolicy().hasHeightForWidth())
        About_window.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(About_window)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(About_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(About_window)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(About_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(About_window)
        self.buttonBox.accepted.connect(About_window.accept)
        QtCore.QMetaObject.connectSlotsByName(About_window)

    def retranslateUi(self, About_window):
        _translate = QtCore.QCoreApplication.translate
        About_window.setWindowTitle(_translate("About_window", "About Coverage Builder"))
        self.label_2.setText(_translate("About_window", "<html><head/><body><p align=\"center\"><img src=\":/plugins/coveragebuilder/icon.png\"/></p><p align=\"center\">Coverage Builder Version 0.5.0</p></body></html>"))
        self.label.setText(_translate("About_window", "<html><head/><body><p align=\"center\">This is an updated version of the &quot;Grids for Atlas&quot; plugin, previously published by:<br/>Experts SIG / <a href=\"https://www.biotope.fr/\"><span style=\" text-decoration: underline; color:#0000ff;\">Biotope</span></a><br/>Bertrand Chaussat<br/>Dmitry Kiselev</p><p align=\"center\">homepage = <a href=\"https://github.com/alisterh/coveragebuilder\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/alisterh/coveragebuilder<br/></span></a>tracker = <a href=\"https://github.com/alisterh/coveragebuilder/issues\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/alisterh/coveragebuilder/issues</span></a></p></body></html>"))
from . import resources
